CREATE TABLE LOCATION (
  LOCATION_ID SERIAL PRIMARY KEY,
  DIVISION TEXT NOT NULL,
  CITY TEXT NOT NULL
);

CREATE TABLE PERSON (
  PERSON_ID SERIAL PRIMARY KEY,
  PERSON_NAME TEXT NOT NULL,
  PASSWORD TEXT NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  PHONE TEXT UNIQUE NOT NULL,
  EMAIL TEXT UNIQUE NOT NULL,
  IMAGE TEXT
);

CREATE TABLE ADDRESS (
  ADDRESS_ID SERIAL PRIMARY KEY,
  PERSON_ID INTEGER,
  LOCATION_ID INTEGER,
  STREET_NAME TEXT NOT NULL,
  HOUSE_NUMBER TEXT NOT NULL,
  POST_CODE INTEGER NOT NULL,
  CONSTRAINT FK_PERSON
    FOREIGN KEY (PERSON_ID)
      REFERENCES PERSON(PERSON_ID)
        ON DELETE CASCADE,
  CONSTRAINT FK_LOCATION
    FOREIGN KEY (LOCATION_ID)
      REFERENCES LOCATION(LOCATION_ID)
        ON DELETE SET NULL
);

CREATE TABLE CATEGORIES (
  CATEGORY_ID SERIAL PRIMARY KEY,
	CATEGORY_NAME TEXT UNIQUE NOT NULL
);

CREATE TABLE STOREFRONT (
  STOREFRONT_ID SERIAL PRIMARY KEY,
  CATEGORY_ID INTEGER,
  STOREFRONT_NAME TEXT NOT NULL,
  STOREFRONT_DESCRIPTION TEXT,
  LAST_UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IMAGE TEXT,
  CONSTRAINT FK_CATEGORY
    FOREIGN KEY (CATEGORY_ID)
      REFERENCES CATEGORIES(CATEGORY_ID)
        ON DELETE SET NULL
);

CREATE TABLE MANAGES (
	PERSON_ID INTEGER,
	STOREFRONT_ID INTEGER,
  CONSTRAINT PK_MANAGES
    PRIMARY KEY (PERSON_ID, STOREFRONT_ID)
);

CREATE TABLE PRODUCT (
  PRODUCT_ID SERIAL PRIMARY KEY,
  STOREFRONT_ID INTEGER,
  PRODUCT_NAME TEXT NOT NULL,
  PRODUCT_DESCRIPTION TEXT NOT NULL,
  STOCK_COUNT INTEGER DEFAULT 50 NOT NULL,
  ITEMS_SOLD INTEGER DEFAULT 0 NOT NULL,
  LAST_UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRICE REAL NOT NULL CHECK (PRICE > 0),
  IMAGE TEXT,
  CONSTRAINT FK_STOREFRONT
    FOREIGN KEY (STOREFRONT_ID)
      REFERENCES STOREFRONT(STOREFRONT_ID)
        ON DELETE CASCADE
);

CREATE TABLE CART (
  PERSON_ID INTEGER,
  PRODUCT_ID INTEGER,
  QUANTITY INTEGER NOT NULL,
  CONSTRAINT PK_CART
    PRIMARY KEY (PERSON_ID, PRODUCT_ID),
  CONSTRAINT FK_PARENT
    FOREIGN KEY (PERSON_ID)
      REFERENCES PERSON(PERSON_ID)
        ON DELETE CASCADE,
  CONSTRAINT FK_CONTAINS
    FOREIGN KEY (PRODUCT_ID)
      REFERENCES PRODUCT(PRODUCT_ID)
        ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS (
  TRANSACTION_ID SERIAL PRIMARY KEY,
  PERSON_ID INTEGER NOT NULL,
  STOREFRONT_ID INTEGER,
  AMOUNT REAL NOT NULL,
	TRANSACTION_TYPE text NOT NULL, -- 0 = BKASH, 1 = NAGAD, 2 = CASH ON DELIVERY
  TRANSACTION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_STORE
    FOREIGN KEY (STOREFRONT_ID)
      REFERENCES STOREFRONT(STOREFRONT_ID)
				ON DELETE SET NULL
);

CREATE TABLE ORDERS (
  ORDER_ID SERIAL PRIMARY KEY,
  PRODUCT_ID INTEGER NOT NULL,
	GROUP_ID INTEGER,
	QUANTITY INTEGER NOT NULL,
  PERSON_ID INTEGER,
  TRANSACTION_ID INTEGER,
	PRICE REAL NOT NULL DEFAULT 0,
  ORDER_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DELIVERY_STATUS INTEGER DEFAULT 0, -- 0 = NOT DELIVERED, 1 = DELIVERED BUT NOT PAID, 2 = PAID
  CONSTRAINT FK_BUYER
    FOREIGN KEY (PERSON_ID)
      REFERENCES PERSON(PERSON_ID)
				ON DELETE SET NULL,
  CONSTRAINT FK_TRANSACTION
    FOREIGN KEY (TRANSACTION_ID)
      REFERENCES TRANSACTIONS(TRANSACTION_ID)
        ON DELETE SET NULL
);

CREATE TABLE ANNOUNCEMENTS (
	ANNOUNCEMENT_ID SERIAL PRIMARY KEY,
	STOREFRONT_ID INTEGER,
	ANNOUNCEMENT_DESCRIPTION TEXT NOT NULL,
	POSTED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IMAGE TEXT,
	PERSON_ID INTEGER NOT NULL,
  CONSTRAINT FK_ANNOUNCEMENT_STOREFRONT_ID
    FOREIGN KEY (STOREFRONT_ID)
      REFERENCES STOREFRONT(STOREFRONT_ID)
        ON DELETE CASCADE
);

CREATE TABLE REVIEW (
	REVIEW_ID SERIAL PRIMARY KEY, 
	PRODUCT_ID INTEGER, 
	PERSON_ID INTEGER, 
	POSTED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	COMMENTS TEXT,
	RATING REAL NOT NULL,
	 CONSTRAINT FK_REVIEW_PERSON
    FOREIGN KEY (PERSON_ID)
      REFERENCES PERSON(PERSON_ID)
        ON DELETE CASCADE,
	CONSTRAINT FK_REVIEW_PRODUCT
		FOREIGN KEY (PRODUCT_ID)
			REFERENCES PRODUCT(PRODUCT_ID)
				ON DELETE CASCADE
);

CREATE TABLE COMPLAINTS (
	COMPLAINT_ID SERIAL PRIMARY KEY,
	PERSON_ID INTEGER,
	STOREFRONT_ID INTEGER,
	POSTED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	COMPLAINT_DETAILS TEXT,
	CONSTRAINT FK_BY
		FOREIGN KEY (PERSON_ID)
			REFERENCES PERSON(PERSON_ID)
				ON DELETE CASCADE,
	CONSTRAINT FK_AGAINST
		FOREIGN KEY (STOREFRONT_ID)
			REFERENCES STOREFRONT(STOREFRONT_ID)
				ON DELETE CASCADE
);

CREATE TABLE TAGS (
	TAG_NAME TEXT PRIMARY KEY
);

CREATE TABLE TAG_ASSIGNMENT (
	PRODUCT_ID INTEGER, 
	TAG_NAME TEXT, 
	CONSTRAINT PK_PRODUCT_RELATION
		PRIMARY KEY(PRODUCT_ID, TAG_NAME),
	CONSTRAINT FK_PRODUCT
		FOREIGN KEY (PRODUCT_ID)
			REFERENCES PRODUCT(PRODUCT_ID)
				ON DELETE CASCADE,
	CONSTRAINT FK_TAG
		FOREIGN KEY(TAG_NAME)
			REFERENCES TAGS(TAG_NAME)
				ON DELETE CASCADE
);


CREATE TABLE ACTION_LOG (
  ACTION_ID SERIAL PRIMARY KEY,
  PERSON_ID INTEGER DEFAULT NULL,
  STOREFRONT_ID INTEGER DEFAULT NULL,
  PRODUCT_ID INTEGER DEFAULT NULL,
  ACTION_TYPE TEXT NOT NULL,
  ACTION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DELETED_PERSON (
  PERSON_ID INTEGER PRIMARY KEY,
  PERSON_NAME TEXT NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  PHONE TEXT NOT NULL,
  EMAIL TEXT NOT NULL
);

CREATE TABLE DELETED_STOREFRONT (
  STOREFRONT_ID INTEGER PRIMARY KEY,
  STOREFRONT_NAME TEXT NOT NULL,
  STOREFRONT_DESCRIPTION TEXT
);

CREATE TABLE DELETED_PRODUCT (
  PRODUCT_ID INTEGER PRIMARY KEY,
  STOREFRONT_ID INTEGER,
  PRODUCT_NAME TEXT NOT NULL,
  PRODUCT_DESCRIPTION TEXT NOT NULL,
  ITEMS_SOLD INTEGER DEFAULT 0 NOT NULL,
  PRICE REAL NOT NULL
);