DROP TABLE IF EXISTS product cascade;
DROP TABLE IF EXISTS announcements cascade;
DROP TABLE IF EXISTS manages cascade;
DROP TABLE IF EXISTS person cascade;
DROP TABLE IF EXISTS storefront cascade;
DROP TABLE IF EXISTS location cascade;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS cart CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS REVIEW CASCADE; 
DROP TABLE IF EXISTS COMPLAINTS CASCADE;
DROP TABLE IF EXISTS TAGS CASCADE;
DROP TABLE IF EXISTS TAG_ASSIGNMENT CASCADE;
DROP TABLE IF EXISTS CATEGORIES CASCADE;

